// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT9W6uf0cD-Qat3b2WaTdWgsSbcPtPDu4',
    appId: '1:586829411860:web:860537265a60461c161901',
    messagingSenderId: '586829411860',
    projectId: 'virtual-eye-ankit-2025',
    authDomain: 'virtual-eye-ankit-2025.firebaseapp.com',
    storageBucket: 'virtual-eye-ankit-2025.firebasestorage.app',
    measurementId: 'G-BL6Y78FJ2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMNPZ6MA-GY9Hzsu9Xq4Cp86kbFq6tHnk',
    appId: '1:586829411860:android:74e9c9b85d559704161901',
    messagingSenderId: '586829411860',
    projectId: 'virtual-eye-ankit-2025',
    storageBucket: 'virtual-eye-ankit-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqgIc6aElFMAI_NIEvh1Sra4G57GbVrQQ',
    appId: '1:586829411860:ios:d78c18175c94ce83161901',
    messagingSenderId: '586829411860',
    projectId: 'virtual-eye-ankit-2025',
    storageBucket: 'virtual-eye-ankit-2025.firebasestorage.app',
    iosBundleId: 'com.virtual.eye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqgIc6aElFMAI_NIEvh1Sra4G57GbVrQQ',
    appId: '1:586829411860:ios:bd2b5124cb4ae27d161901',
    messagingSenderId: '586829411860',
    projectId: 'virtual-eye-ankit-2025',
    storageBucket: 'virtual-eye-ankit-2025.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT9W6uf0cD-Qat3b2WaTdWgsSbcPtPDu4',
    appId: '1:586829411860:web:d02e4dc043d86aab161901',
    messagingSenderId: '586829411860',
    projectId: 'virtual-eye-ankit-2025',
    authDomain: 'virtual-eye-ankit-2025.firebaseapp.com',
    storageBucket: 'virtual-eye-ankit-2025.firebasestorage.app',
    measurementId: 'G-JX1L1JWGEX',
  );
}
